import type { CardDefinition, CardId } from '../types.ts'

export const cardDefinitions: Record<CardId, CardDefinition> = {
  strike: {
    id: 'strike',
    name: 'Strike',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'starter',
    cost: 1,
    description: 'Deal 6 damage.',
    upgradedDescription: 'Deal 9 damage.',
    effect: { damage: 6 },
    upgradedEffect: { damage: 9 },
  },
  defend: {
    id: 'defend',
    name: 'Defend',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'starter',
    cost: 1,
    description: 'Gain 5 Block.',
    upgradedDescription: 'Gain 8 Block.',
    effect: { block: 5 },
    upgradedEffect: { block: 8 },
  },
  bash: {
    id: 'bash',
    name: 'Bash',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'starter',
    cost: 2,
    description: 'Deal 8 damage. Apply 2 Vulnerable.',
    upgradedDescription: 'Deal 10 damage. Apply 3 Vulnerable.',
    effect: { damage: 8, applyVulnerable: 2 },
    upgradedEffect: { damage: 10, applyVulnerable: 3 },
  },
  anger: {
    id: 'anger',
    name: 'Anger',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 0,
    description: 'Deal 6 damage. Add a copy of this card into your discard pile.',
    upgradedDescription: 'Deal 8 damage. Add a copy of this card into your discard pile.',
    effect: { damage: 6, createCopyInDiscard: true },
    upgradedEffect: { damage: 8, createCopyInDiscard: true },
  },
  armaments: {
    id: 'armaments',
    name: 'Armaments',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: 'Gain 5 Block. Upgrade a card in your Hand for the rest of combat.',
    upgradedDescription: 'Gain 5 Block. Upgrade ALL cards in your Hand for the rest of combat.',
    effect: { block: 5, upgradeChosenHandCard: true },
    upgradedEffect: { block: 5, upgradeAllHand: true },
  },
  'blood-wall': {
    id: 'blood-wall',
    name: 'Blood Wall',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 2,
    description: 'Lose 2 HP. Gain 16 Block.',
    upgradedDescription: 'Lose 2 HP. Gain 20 Block.',
    effect: { loseHpSelf: 2, block: 16 },
    upgradedEffect: { loseHpSelf: 2, block: 20 },
  },
  bloodletting: {
    id: 'bloodletting',
    name: 'Bloodletting',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    description: 'Lose 3 HP. Gain 2 Energy.',
    upgradedDescription: 'Lose 3 HP. Gain 3 Energy.',
    effect: { loseHpSelf: 3, gainEnergy: 2 },
    upgradedEffect: { loseHpSelf: 3, gainEnergy: 3 },
  },
  'body-slam': {
    id: 'body-slam',
    name: 'Body Slam',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    upgradedCost: 0,
    description: 'Deal damage equal to your Block.',
    upgradedDescription: 'Deal damage equal to your Block.',
    effect: { damageEqualsBlock: true },
    upgradedEffect: { damageEqualsBlock: true },
  },
  breakthrough: {
    id: 'breakthrough',
    name: 'Breakthrough',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Lose 1 HP. Deal 9 damage to all enemies.',
    upgradedDescription: 'Lose 1 HP. Deal 13 damage to all enemies.',
    effect: { loseHpSelf: 1, damageAll: 9 },
    upgradedEffect: { loseHpSelf: 1, damageAll: 13 },
  },
  bludgeon: {
    id: 'bludgeon',
    name: 'Bludgeon',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'uncommon',
    cost: 3,
    description: 'Deal 32 damage.',
    upgradedDescription: 'Deal 42 damage.',
    effect: { damage: 32 },
    upgradedEffect: { damage: 42 },
  },
  bully: {
    id: 'bully',
    name: 'Bully',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 0,
    description: 'Deal 5 damage. Deal 2 additional damage for each Vulnerable on the enemy.',
    upgradedDescription: 'Deal 7 damage. Deal 3 additional damage for each Vulnerable on the enemy.',
    effect: { damage: 5, scaleWithEnemyVulnerable: 2 },
    upgradedEffect: { damage: 7, scaleWithEnemyVulnerable: 3 },
  },
  'burning-pact': {
    id: 'burning-pact',
    name: 'Burning Pact',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: 'Exhaust a card in your hand. Draw 2 cards.',
    upgradedDescription: 'Exhaust a card in your hand. Draw 3 cards.',
    effect: { exhaustChosenHandCard: true, drawCardsAfterChosenExhaust: 2 },
    upgradedEffect: { exhaustChosenHandCard: true, drawCardsAfterChosenExhaust: 3 },
  },
  cinder: {
    id: 'cinder',
    name: 'Cinder',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    description: 'Deal 17 damage. Exhaust the top card of your draw pile.',
    upgradedDescription: 'Deal 22 damage. Exhaust the top card of your draw pile.',
    effect: { damage: 17, exhaustTopDrawPile: 1 },
    upgradedEffect: { damage: 22, exhaustTopDrawPile: 1 },
  },
  entrench: {
    id: 'entrench',
    name: 'Entrench',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    description: 'Double your Block.',
    upgradedDescription: 'Double your Block.',
    effect: { doubleBlock: true },
    upgradedEffect: { doubleBlock: true },
  },
  'evil-eye': {
    id: 'evil-eye',
    name: 'Evil Eye',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    description: 'Gain 8 Block. Gain another 8 Block if you have Exhausted a card this turn.',
    upgradedDescription: 'Gain 11 Block. Gain another 11 Block if you have Exhausted a card this turn.',
    effect: { block: 8, bonusBlockIfExhaustedThisTurn: 8 },
    upgradedEffect: { block: 11, bonusBlockIfExhaustedThisTurn: 11 },
  },
  'expect-a-fight': {
    id: 'expect-a-fight',
    name: 'Expect a Fight',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 2,
    description: 'Gain 1 Energy for each Attack in your hand.',
    upgradedDescription: 'Gain 2 Energy for each Attack in your hand.',
    effect: { gainEnergyPerAttackInHand: 1 },
    upgradedEffect: { gainEnergyPerAttackInHand: 2 },
  },
  'feel-no-pain': {
    id: 'feel-no-pain',
    name: 'Feel No Pain',
    classId: 'ironclad',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    description: 'Whenever a card is Exhausted, gain 3 Block.',
    upgradedDescription: 'Whenever a card is Exhausted, gain 4 Block.',
    effect: { feelNoPainBlock: 3 },
    upgradedEffect: { feelNoPainBlock: 4 },
  },
  feed: {
    id: 'feed',
    name: 'Feed',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    description: 'Deal 10 damage. If Fatal, raise your Max HP by 3. Exhaust.',
    upgradedDescription: 'Deal 12 damage. If Fatal, raise your Max HP by 4. Exhaust.',
    effect: { damage: 10, fatalMaxHpGain: 3, exhaustSelf: true },
    upgradedEffect: { damage: 12, fatalMaxHpGain: 4, exhaustSelf: true },
  },
  'fiend-fire': {
    id: 'fiend-fire',
    name: 'Fiend Fire',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    description: 'Exhaust your hand. Deal 7 damage for each Exhausted card. Exhaust.',
    upgradedDescription: 'Exhaust your hand. Deal 10 damage for each Exhausted card. Exhaust.',
    effect: { exhaustEntireHandForDamage: 7, exhaustSelf: true },
    upgradedEffect: { exhaustEntireHandForDamage: 10, exhaustSelf: true },
  },
  'fight-me': {
    id: 'fight-me',
    name: 'Fight Me!',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    description: 'Deal 5 damage twice. Gain 2 Strength. The target gains 1 Strength.',
    upgradedDescription: 'Deal 6 damage twice. Gain 3 Strength. The target gains 1 Strength.',
    effect: { damage: 5, hits: 2, gainTemporaryStrength: 2, gainEnemyStrength: 1 },
    upgradedEffect: { damage: 6, hits: 2, gainTemporaryStrength: 3, gainEnemyStrength: 1 },
  },
  'flame-barrier': {
    id: 'flame-barrier',
    name: 'Flame Barrier',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    description: 'Gain 12 Block. Whenever you are attacked this turn, deal 4 damage back.',
    upgradedDescription: 'Gain 16 Block. Whenever you are attacked this turn, deal 6 damage back.',
    effect: { block: 12, retaliateDamageThisTurn: 4 },
    upgradedEffect: { block: 16, retaliateDamageThisTurn: 6 },
  },
  havoc: {
    id: 'havoc',
    name: 'Havoc',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    upgradedCost: 0,
    description: 'Play the top card of your draw pile and Exhaust it.',
    upgradedDescription: 'Play the top card of your draw pile and Exhaust it.',
    effect: { playTopDrawPileAndExhaust: true },
    upgradedEffect: { playTopDrawPileAndExhaust: true },
  },
  headbutt: {
    id: 'headbutt',
    name: 'Headbutt',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Deal 9 damage. Put a card from your Discard Pile on top of your Draw Pile.',
    upgradedDescription: 'Deal 12 damage. Put a card from your Discard Pile on top of your Draw Pile.',
    effect: { damage: 9, moveDiscardToDrawTop: true },
    upgradedEffect: { damage: 12, moveDiscardToDrawTop: true },
  },
  inflame: {
    id: 'inflame',
    name: 'Inflame',
    classId: 'ironclad',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    description: 'Gain 2 Strength.',
    upgradedDescription: 'Gain 3 Strength.',
    effect: { gainStrength: 2 },
    upgradedEffect: { gainStrength: 3 },
  },
  impervious: {
    id: 'impervious',
    name: 'Impervious',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    description: 'Gain 30 Block. Exhaust.',
    upgradedDescription: 'Gain 40 Block. Exhaust.',
    effect: { block: 30, exhaustSelf: true },
    upgradedEffect: { block: 40, exhaustSelf: true },
  },
  'iron-wave': {
    id: 'iron-wave',
    name: 'Iron Wave',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Gain 5 Block. Deal 5 damage.',
    upgradedDescription: 'Gain 7 Block. Deal 7 damage.',
    effect: { block: 5, damage: 5 },
    upgradedEffect: { block: 7, damage: 7 },
  },
  'molten-fist': {
    id: 'molten-fist',
    name: 'Molten Fist',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: "Deal 10 damage. Double the enemy's Vulnerable. Exhaust.",
    upgradedDescription: "Deal 14 damage. Double the enemy's Vulnerable. Exhaust.",
    effect: { damage: 10, doubleEnemyVulnerable: true, exhaustSelf: true },
    upgradedEffect: { damage: 14, doubleEnemyVulnerable: true, exhaustSelf: true },
  },
  'perfected-strike': {
    id: 'perfected-strike',
    name: 'Perfected Strike',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    description: 'Deal 6 damage. Deals 2 additional damage for all your cards containing "Strike".',
    upgradedDescription: 'Deal 6 damage. Deals 3 additional damage for all your cards containing "Strike".',
    effect: { damage: 6, scaleWithStrikeCards: 2 },
    upgradedEffect: { damage: 6, scaleWithStrikeCards: 3 },
  },
  'pommel-strike': {
    id: 'pommel-strike',
    name: 'Pommel Strike',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Deal 9 damage. Draw 1 card.',
    upgradedDescription: 'Deal 10 damage. Draw 2 cards.',
    effect: { damage: 9, drawCards: 1 },
    upgradedEffect: { damage: 10, drawCards: 2 },
  },
  'setup-strike': {
    id: 'setup-strike',
    name: 'Setup Strike',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Deal 7 damage. Gain 2 Strength this turn.',
    upgradedDescription: 'Deal 9 damage. Gain 3 Strength this turn.',
    effect: { damage: 7, gainTemporaryStrength: 2 },
    upgradedEffect: { damage: 9, gainTemporaryStrength: 3 },
  },
  'shrug-it-off': {
    id: 'shrug-it-off',
    name: 'Shrug It Off',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: 'Gain 8 Block. Draw 1 card.',
    upgradedDescription: 'Gain 11 Block. Draw 1 card.',
    effect: { block: 8, drawCards: 1 },
    upgradedEffect: { block: 11, drawCards: 1 },
  },
  'sword-boomerang': {
    id: 'sword-boomerang',
    name: 'Sword Boomerang',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Deal 3 damage to a random enemy 3 times.',
    upgradedDescription: 'Deal 3 damage to a random enemy 4 times.',
    effect: { damage: 3, hits: 3, randomTarget: true },
    upgradedEffect: { damage: 3, hits: 4, randomTarget: true },
  },
  thunderclap: {
    id: 'thunderclap',
    name: 'Thunderclap',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Deal 4 damage and apply 1 Vulnerable to all enemies.',
    upgradedDescription: 'Deal 7 damage and apply 1 Vulnerable to all enemies.',
    effect: { damageAll: 4, applyVulnerableAll: 1 },
    upgradedEffect: { damageAll: 7, applyVulnerableAll: 1 },
  },
  tremble: {
    id: 'tremble',
    name: 'Tremble',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: 'Apply 2 Vulnerable.',
    upgradedDescription: 'Apply 3 Vulnerable.',
    effect: { applyVulnerable: 2, targetEnemy: true },
    upgradedEffect: { applyVulnerable: 3, targetEnemy: true },
  },
  'true-grit': {
    id: 'true-grit',
    name: 'True Grit',
    classId: 'ironclad',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: 'Gain 7 Block. Exhaust a random card in your hand.',
    upgradedDescription: 'Gain 9 Block. Exhaust a card in your hand.',
    effect: { block: 7, exhaustRandomHandCard: true },
    upgradedEffect: { block: 9, exhaustChosenHandCard: true },
  },
  'twin-strike': {
    id: 'twin-strike',
    name: 'Twin Strike',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Deal 5 damage twice.',
    upgradedDescription: 'Deal 6 damage twice.',
    effect: { damage: 5, hits: 2 },
    upgradedEffect: { damage: 6, hits: 2 },
  },
  'ashen-strike': {
    id: 'ashen-strike',
    name: 'Ashen Strike',
    classId: 'ironclad',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: 'Deal 5 damage. Deal 2 additional damage for each card in your Exhaust pile.',
    upgradedDescription: 'Deal 7 damage. Deal 2 additional damage for each card in your Exhaust pile.',
    effect: { damage: 5, scaleWithExhaustPile: 2 },
    upgradedEffect: { damage: 7, scaleWithExhaustPile: 2 },
  },
}

export const rewardCardPool: CardId[] = [
  'anger',
  'armaments',
  'blood-wall',
  'bloodletting',
  'body-slam',
  'breakthrough',
  'bludgeon',
  'bully',
  'burning-pact',
  'cinder',
  'entrench',
  'evil-eye',
  'expect-a-fight',
  'feel-no-pain',
  'feed',
  'fiend-fire',
  'fight-me',
  'flame-barrier',
  'havoc',
  'headbutt',
  'inflame',
  'impervious',
  'iron-wave',
  'molten-fist',
  'perfected-strike',
  'pommel-strike',
  'setup-strike',
  'shrug-it-off',
  'sword-boomerang',
  'thunderclap',
  'tremble',
  'true-grit',
  'twin-strike',
  'ashen-strike',
]
